apiVersion: v1
kind: Pod
metadata:
  name: redis-dev
  namespace: jejuonul-dev
  labels:
    app: redis-dev
    app.kubernetes.io/instance: redis-dev
spec:
  containers:
    - name: redis-dev
      image: redis
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: '4'
          memory: 8Gi
        requests:
          cpu: '4'
          memory: 8Gi
