apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: redis-dev
  name: redis-dev-service
  namespace: jejuonul-dev
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-dev
  type: LoadBalancer
