apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: payment-consumer-dev
  name: payment-consumer-dev-service
  namespace: jejuonul-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: payment-consumer-dev
  type: ClusterIP
