apiVersion: v1
kind: Pod
metadata:
  labels:
    app: api-gateway-dev
    app.kubernetes.io/instance: api-gateway-dev
  name: api-gateway-dev
  namespace: jejuonul-dev
spec:
  containers:
    - image: 'jejuonul-api-dev.kr.ncr.ntruss.com/api-gateway-dev:1.1'
      name: api-gateway-dev
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: ncr-secret