apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: api-gateway-dev
  name: api-gateway-dev-service
  namespace: jejuonul-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: api-gateway-dev
  type: LoadBalancer
