apiVersion: v1
kind: Service
metadata:
  name: auth-api-dev-service
  namespace: jejuonul-dev-test
  labels:
    app: auth-api-dev
    app.kubernetes.io/instance: auth-api-dev
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: auth-api-dev
