apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: user-consumer-dev
  name: user-consumer-dev-service
  namespace: jejuonul-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: user-consumer-dev
  type: ClusterIP
