apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer-dev
  namespace: jejuonul-dev-test
  labels:
    app: order-consumer-dev
    app.kubernetes.io/instance: order-consumer-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-consumer-dev
  template:
    metadata:
      labels:
        app: order-consumer-dev
        app.kubernetes.io/instance: order-consumer-dev
    spec:
      containers:
        - name: order-consumer-dev
          image: 'jejuonul-api-dev.kr.ncr.ntruss.com/order-consumer-dev:1.0'
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      imagePullSecrets:
        - name: ncr-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-consumer-dev
  namespace: jejuonul-dev-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-consumer-dev
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90

