apiVersion: v1
kind: Pod
metadata:
  labels:
    app: common-api-dev
    app.kubernetes.io/instance: common-api-dev
  name: common-api-dev
  namespace: jejuonul-dev
spec:
  containers:
    - image: 'jejuonul-api-dev.kr.ncr.ntruss.com/common-api-dev:0.7'
      name: common-api-dev
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: ncr-secret
