apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: auth-api-dev
  name: auth-api-dev-service
  namespace: jejuonul-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: auth-api-dev
  type: ClusterIP