apiVersion: v1
kind: Pod
metadata:
  labels:
    app: routing-api-dev
    app.kubernetes.io/instance: routing-api-dev
  name: routing-api-dev
  namespace: jejuonul-dev-test
spec:
  containers:
    - image: 'jejuonul-api-dev.kr.ncr.ntruss.com/routing-api-dev:0.7'
      name: routing-api-dev
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: ncr-secret
