apiVersion: v1
kind: Pod
metadata:
  labels:
    app: payment-api-dev
    app.kubernetes.io/instance: payment-api-dev
  name: payment-api-dev
  namespace: jejuonul-dev
spec:
  containers:
    - image: 'jejuonul-api-dev.kr.ncr.ntruss.com/payment-api-dev:0.8'
      name: payment-api-dev
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: ncr-secret
