apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api-dev
  namespace: jejuonul-dev-test
  labels:
    app: payment-api-dev
    app.kubernetes.io/instance: payment-api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api-dev
  template:
    metadata:
      labels:
        app: payment-api-dev
        app.kubernetes.io/instance: payment-api-dev
    spec:
      containers:
        - name: payment-api-dev
          image: 'jejuonul-api-dev.kr.ncr.ntruss.com/payment-api-dev:0.8'
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      imagePullSecrets:
        - name: ncr-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-api-dev
  namespace: jejuonul-dev-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-api-dev
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
