apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    argocd.argoproj.io/instance: nginx-test
  name: nginx-deployment
  namespace: nginx-test-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: ubuntu/apache2
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
      imagePullSecrets:
      - name: ncr-secret


