apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: jejuonul-api-dev.kr.ncr.ntruss.com/jeju-order-api
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: ncr-secret

