apiVersion: v1
kind: Pod
metadata:
  name: argocd-helloworld
  labels:
    name: argocd-helloworld
spec:
  containers:
  - name: argocd-helloworld
    image: jejuonul-api-dev.kr.ncr.ntruss.com/ghcr.io/project-osrm/jejuonul-api-dev-nginx/nginx:latest
    resources:
      limits:
        memory: "64Mi"
        cpu: "0.2"
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: ncr-secret
