apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-dev
  namespace: jejuonul-dev
  labels:
    app: order-api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api-dev
  template:
    metadata:
      labels:
        app: order-api-dev
    spec:
      containers:
      - name: order-api-dev
        image: jejuonul-api-dev.kr.ncr.ntruss.com/order-api-dev:1.8
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
      imagePullSecrets:
      - name: ncr-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-api-dev
  namespace: jejuonul-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-api-dev
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
