apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: order-api
  name: api-service
  namespace: jejuonul-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: api
  type: ClusterIP
