apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: order-api-dev
  name: order-api-dev-service
  namespace: test123
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: order-api-dev
  type: ClusterIP
