apiVersion: v1
kind: Service
metadata:
    name: order-api-dev-service
    namespace: test123
spec:
    selector:
        app: order-api-dev
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
    type: ClusterIP
