apiVersion: v1
kind: Service
metadata:
  name: api-gateway-dev-service
  namespace: jejuonul-dev
  labels:
    app: api-gateway-dev
    app.kubernetes.io/instance: api-gateway-dev
    argocd.argoproj.io/instance: api-gateway-dev
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-gateway-dev
